version: '3.7'

services:
  web:
    image: docs:1.0
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 100M
          cpus: '0.1'
    logging:
      driver: ".devconteiner/devcontainer.json"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "80:80"    
    networks:
      - my_network
networks:
  my_network:
    driver: overlay
      
